CREATE OR REPLACE TABLE `vast-cogency-464203-t0.strava_activity_upload.strava_data_cleaned` AS
SELECT
    id,
    name,
    type,
    sport_type AS subtype,
    ROUND(moving_time / 60.0, 2) AS moving_time_mins,
    ROUND(elapsed_time / 60.0, 2) AS elapsed_time_mins,
    ROUND(distance / 1609.344, 2) AS distance_miles,
    total_elevation_gain,
    DATE(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', start_date_local)) AS local_start_date,
    TIME(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', start_date_local)) AS local_start_time,
    timezone,
    SUBSTR(timezone, STRPOS(timezone, ')') + 2) AS timezone_name,
    kudos_count,
    start_latlng,
    end_latlng,
    start_latlng[SAFE_OFFSET(0)] AS start_latitude,
    start_latlng[SAFE_OFFSET(1)] AS start_longitude,
    end_latlng[SAFE_OFFSET(0)] AS end_latitude,
    end_latlng[SAFE_OFFSET(1)] AS end_longitude,
    ROUND(average_speed * 2.23694, 2) AS average_speed_mph,
    ROUND(max_speed * 2.23694, 2) AS max_speed_mph,
    average_heartrate,
    max_heartrate,
    average_cadence,
    average_watts,
    kilojoules,
    ROUND(elev_high / 3.280839, 2) AS elevation_high,
    ROUND(elev_low / 3.280839, 2) AS elevation_low,
    ROUND(total_elevation_gain / 3.280839, 2) AS elevation_gain
FROM `vast-cogency-464203-t0.strava_activity_upload.strava_data_allactivities`;
