CREATE OR REPLACE TABLE `vast-cogency-464203-t0.strava_activity_upload.strava_data_cleaned` AS
SELECT
    id,
    name,
    type,
    sport_type AS subtype,
    ROUND(moving_time / 60.0, 2) AS moving_time_mins,
    ROUND(elapsed_time / 60.0, 2) AS elapsed_time_mins,
    ROUND(distance / 1609.344, 2) AS distance_miles,
    total_elevation_gain,
    DATE(start_date_local) AS local_start_date,
    TIME(start_date_local) AS local_start_time,
    timezone,
    SUBSTR(timezone, INSTR(timezone, ')') + 2) AS timezone_name,
    kudos_count,
    start_latlng,
    end_latlng,
    TRIM(REPLACE(SUBSTR(start_latlng, 2, INSTR(start_latlng, ',') - 1), ']', '')) AS start_latitude,
    TRIM(REPLACE(SUBSTR(start_latlng, INSTR(start_latlng, ',') + 2), ']', '')) AS start_longitude,
    TRIM(REPLACE(SUBSTR(end_latlng, 2, INSTR(end_latlng, ',') - 1), ']', '')) AS end_latitude,
    TRIM(REPLACE(SUBSTR(end_latlng, INSTR(end_latlng, ',') + 2), ']', '')) AS end_longitude,
    ROUND(average_speed * 2.23694, 2) AS average_speed_mph,
    ROUND(max_speed * 2.23694, 2) AS max_speed_mph,
    average_heartrate,
    max_heartrate,
    average_cadence,
    average_watts,
    kilojoules,
    ROUND(elev_high / 3.280839, 2) AS elevation_high,
    ROUND(elev_low / 3.280839, 2) AS elevation_low,
    ROUND(total_elevation_gain / 3.280839, 2) AS elevation_gain
FROM `vast-cogency-464203-t0.strava_activity_upload.strava_activity_upload`;
