name: Weekly Strava Sync

on:
  schedule:
    - cron: '0 12 * * 1'   # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # make sure oauth + gbq are available even if not in requirements.txt
          pip install google-auth-oauthlib pandas-gbq>=0.26.1

      - name: Decode GCP service account (for BigQuery)
        shell: bash
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 -d > /tmp/credentials.json

      - name: Export environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json" >> $GITHUB_ENV
          echo "DRIVE_FOLDER_ID=${{ secrets.DRIVE_FOLDER_ID }}" >> $GITHUB_ENV
          echo "DRIVE_CLIENT_ID=${{ secrets.DRIVE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "DRIVE_CLIENT_SECRET=${{ secrets.DRIVE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "DRIVE_REFRESH_TOKEN=${{ secrets.DRIVE_REFRESH_TOKEN }}" >> $GITHUB_ENV

      - name: Run data pull + transform + uploads
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python strava_data_pull.py